# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Public Goods Lottery Indexer
networks:
- id: 84532
  start_block: 14535680
  contracts:
  - name: PublicGoodsLottery
    address:
    - 0xaE54219f64AE47881f98c9aF65ed424bcDCbcB07
    handler: src/EventHandlers.ts
    events:
    - event: LotteryCreated(uint256 indexed lotteryId, uint256 indexed expiration, address indexed receiver)
    - event: TicketPurchased(uint256 indexed lotteryId, uint256 indexed ticketId, address indexed receiver, uint256 amount, uint256 value)
    - event: LotteryEnded(uint256 indexed lotteryId, address[] winners, uint256[] winnersValues)