# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Public Goods Lottery Indexer
networks:
- id: 84532
  start_block: 	14895680
  contracts:
  - name: PublicGoodsLottery
    address:
    - 0x19C1C374fDB513DA78CdE1202FBf2B0c56c5cdDc
    handler: src/EventHandlers.ts
    events:
    - event: LotteryCreated(uint256 indexed lotteryId, string name, string description, uint256 indexed expiration, address indexed receiver)
    - event: TicketPurchased(uint256 indexed lotteryId, uint256 indexed ticketId, address indexed receiver, uint256 amount, uint256 value)
    - event: LotteryEndRequested(uint256 indexed lotteryId, uint256 indexed vrfRequestId)
    - event: LotteryEnded(uint256 indexed lotteryId, address[] winners, uint256[] winnersValues)